
[package]
name = "qleany"
version = "0.0.0"
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
slint = "1.8.0"

[build-dependencies]
slint-build = "1.8.0"