[book]
title = "Qleany Documentation"
authors = ["Cyril Jacquet"]
language = "en"
src = "docs"

[output.html]
git-repository-url = "https://github.com/jacquetc/qleany"
edit-url-template = "https://github.com/jacquetc/qleany/edit/main/{path}"
