[workspace]

members = ["crates/*"]

resolver = "2"

[workspace.package]
homepage = "https://github.com/jacquetc/qleany"
repository = "https://github.com/jacquetc/qleany"
license = "MPL-2.0"
edition = "2021"

[workspace.dependencies]
thiserror = "2.0.11"
anyhow = "1.0"
redb = "2.4.0" 

[workspace.lints.rust]

