[workspace]

members = [
    "crates/common", 
    "crates/gui", 
    "crates/cli", 
    "crates/direct_access", 
    "crates/handling_manifest",
    "crates/cpp_qt_file_listing",
    "crates/python_file_listing",
    ]

resolver = "2"

[workspace.package]
homepage = "https://github.com/jacquetc/qleany"
repository = "https://github.com/jacquetc/qleany"
license = "MPL-2.0"
edition = "2021"

[workspace.dependencies]
thiserror = "2.0.11"
anyhow = "1.0"
redb = "2.4.0" 
flume = "0.11.1"

[workspace.lints.rust]

