[workspace]

members = [
    "crates/common",
    "crates/cli",
    "crates/direct_access",
    "crates/handling_manifest",
    "crates/cpp_qt_file_generation",
    "crates/python_file_generation",
    "crates/rust_file_generation",
    "crates/slint_ui",
    "crates/macros",
]
default-members = [
    "crates/slint_ui",
]

resolver = "2"

[workspace.package]
homepage = "https://github.com/jacquetc/qleany"
repository = "https://github.com/jacquetc/qleany"
license = "MPL-2.0"
edition = "2024"
version = "2.0.0"

[workspace.dependencies]
thiserror = "2.0.11"
anyhow = "1.0"
flume = "0.11.1"
serde = { version = "1", features = ["derive"] }

[workspace.lints.rust]

