[workspace]

members = ["crates/*"]

resolver = "2"

[workspace.package]
homepage = "https://github.com/jacquetc/qleany"
repository = "https://github.com/jacquetc/qleany"
license = "MPL-2.0"
edition = "2021"

[workspace.dependencies]
thiserror = "2.0.9"

[workspace.lints.rust]

