[workspace]

members = [
    "crates/common",
    "crates/direct_access",
    "crates/handling_manifest",
    "crates/cpp_qt_file_generation",
    "crates/rust_file_generation",
    "crates/handling_app_lifecycle",
    "crates/slint_ui",
    "crates/macros",
]
default-members = [
    "crates/slint_ui",
]

resolver = "2"

[workspace.package]
homepage = "https://github.com/jacquetc/qleany"
repository = "https://github.com/jacquetc/qleany"
license = "MPL-2.0"
edition = "2024"
version = "1.0.4"
authors = ["Cyril Jacquet <cyril.jacquet@ferntech.eu>"]
documentation = "https://docs.rs/qleany/"
readme = "README.md"
description = """
Scaffold code generator for Rust and C++/Qt CLI and GUI applications. Tool UI is made with Slint.
"""
keywords = ["scaffold", "codegen", "rust", "cpp", "qt"]
categories = ["development-tools", "template-engine", "gui", "command-line-utilities", "data-structures"]

[workspace.dependencies]
thiserror = "2.0"
anyhow = "1.0"
flume = "0.12.0"
serde = { version = "1", features = ["derive"] }

[workspace.lints.rust]

