[package]
name = "qleany"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
slint = { version = "1.13.1", features = ["renderer-skia"] }
log = "0.4"
env_logger = "0.11"
rfd = "0.17.2"
dirs = "6.0"
clap = { version = "4.5", features = ["derive"] }

# Backend crates
common = { path = "../common" }
direct_access = { path = "../direct_access" }
handling_manifest = { path = "../handling_manifest" }
rust_file_generation = { path = "../rust_file_generation" }
handling_app_lifecycle = { path = "../handling_app_lifecycle" }
anyhow = {workspace = true}
serde_json = "1.0.149"
serde_yml = "0.0.12"
ctrlc = "3.5.0"
heck = "0.5"

[build-dependencies]
slint-build = "1.13.1"

[lints]
workspace = true