[package]
name = "qleany"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
thiserror = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "1" }
anyhow = { workspace = true }
serde_json = "1.0"
slint = {  version = "1.14", features = ["renderer-skia"] }

[build-dependencies]
slint-build = "1.14"

[lints]
workspace = true