[package]
name = "direct_access"
version = "0.0.0"
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror =  { workspace = true }
common_entities = { path = "../common_entities"}
common = { path = "../common"}


[lints]
workspace = true

