[package]
name = "common"
version = "0.0.0"
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
thiserror =  { workspace = true }
common_entities = { path = "../common_entities"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusqlite = "0.32.1"
tempfile = "3.2.0"
anyhow = "1.0"

[lints]
workspace = true
